### PR TITLE
Fix relative MD links when embedding

### LINKED ISSUE #28: Broken links on `/running-server`
Unfortunately, most of the links on the "running server" page (https://github.com/sourcifyeth/docs/blob/main/docs/2.%20Running%20Sourcify/1-Server.mdx) are broken: https://docs.sourcify.dev/docs/running-server/

Many of these are relative links to files in the Sourcify repository or anchor links which do not appear to be functional on the docs website.

### PR DESCRIPTION
**Pull request by kuzdogan**
This fixes the issue of having relative links (like `../services/database`) in the README.md documents we are embedding in docs.

Now we first process the relative links and turn them into absolute links to full github.com URLs.

Fixes #28

### CODE REVIEW

File: docs/EmbedReadme.js [hunk 1]
```diff
@@ -1,15 +1,42 @@
...
+          }
+
+          return `[${title}](${pageBaseUrl}/${repo}/tree/${branch}/${resolvedPath.join("/")})`;
+        });
+        setContent(parse(processedText));
+      });
   }, []);
 
-  if (!content) return "Loading from " + url + "...";
+  console.log(rawBaseUrl);
```
Comment (manuelwedler) [inline docs/EmbedReadme.js:38]: This can be removed

File: docs/2. Running Sourcify/3-Monitor.mdx [hunk 2]
```diff
@@ -4,9 +4,12 @@ slug: /running-monitor
...
-const displayURL = URL.replace("https://raw.githubusercontent.com/", "");
-export const ReadmeLink = () => (<a href={URL}>{displayURL}</a>);
+const repo = "ethereum/sourcify";
+const branch = "master";
+const readmePath = "/services/monitor/README.md";
+const rawBaseUrl = "https://raw.githubusercontent.com";
+const pageBaseUrl = "https://github.com";
+export const ReadmeLink = () => (<a href={`${pageBaseUrl}/${repo}/tree/${branch}${readmePath}`}>{repo + readmePath}</a>);
 
 *Content from <ReadmeLink/>*
```
Comment (manuelwedler) [inline docs/2. Running Sourcify/3-Monitor.mdx:14]: This part could be refactored to `EmbedReadme`

**Review by manuelwedler — APPROVED** [review]
looks good to me. Just two nitpicks you can fix before merging if you think it makes sense.
